### ISSUE TITLE
Cannot build sherpa

### ISSUE THREAD

**Issue by svandiekendialpad** [k2-fsa/sherpa#181]
CUDA 11.3
PyTorch 1.12.1
k2 fresh dev build (1.21)
I follow sherpa's install instructions (git clone, pip install -r ./requirements.txt, python setup.py install --verbose) which fails with this error:
```
-- Generated /workspace/sherpa/build/temp.linux-x86_64-3.7/sherpa/csrc/version.h
CMake Error at sherpa/csrc/CMakeLists.txt:117 (install):
  install TARGETS given target "kaldi_native_io_core" which does not exist in
  this directory.


-- Configuring incomplete, errors occurred!
See also "/workspace/sherpa/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
See also "/workspace/sherpa/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
make: *** No rule to make target 'install'.  Stop.
Traceback (most recent call last):
  File "setup.py", line 117, in <module>
    license="Apache licensed, as found in the LICENSE file",
  File "/opt/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/opt/conda/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/conda/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/opt/conda/lib/python3.7/site-packages/setuptools/command/install.py", line 116, in do_egg_install
    self.run_command('bdist_egg')
  File "/opt/conda/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/opt/conda/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/opt/conda/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/opt/conda/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/opt/conda/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/opt/conda/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/opt/conda/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/opt/conda/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/workspace/sherpa/cmake/cmake_extension.py", line 117, in build_extension
    "\nBuild sherpa failed. Please check the error message.\n"
Exception:
Build sherpa failed. Please check the error message.
```

**Comment by csukuangfj** [comment]
Could you upgrade your cmake?

pip install cmake

should work.


I will make a change to CMakeLists.txt to enforce that.
