### ISSUE TITLE
Incompatible constructor arguments error

### ISSUE THREAD

**Issue by MolochKel** [k2-fsa/sherpa#197]
Hi, I updated to sherpa v1.0, but I'm now facing the following error whenever I try to start an offline server.

```
2022-11-09 08:45:11,127 INFO [offline_server.py:664] {'decoding_method': 'greedy_search', 'beam': 10.0, 'num_paths': 200, 'num_active_paths': 4, 'nbest_scale': 0.5, 'temperature': 1.0, 'max_contexts': 8, 'max_states': 32, 'lang_dir': PosixPath('data/lang_bpe_500'), 'ngram_lm_scale': 0.01, 'port': 6006, 'num_device': 0, 'max_batch_size': 10, 'max_wait_ms': 5.0, 'feature_extractor_pool_size': 5, 'nn_pool_size': 1, 'nn_model_filename': './exp/cpu_jit-iter-3488000-avg-15.pt', 'bpe_model_filename': './data/lang_bpe_500/bpe.model', 'token_filename': None, 'max_message_size': 1048576, 'max_queue_size': 32, 'max_active_connections': 500, 'certificate': None, 'use_fp16': False, 'doc_root': './sherpa/bin/web'}
Traceback (most recent call last):
  File "/k2-sherpa/sherpa/bin/pruned_transducer_statelessX/offline_server.py", line 762, in <module>
    main()
  File "/opt/conda/envs/k2-sherpa/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/k2-sherpa/sherpa/bin/pruned_transducer_statelessX/offline_server.py", line 716, in main
    offline_server = OfflineServer(
  File "/k2-sherpa/sherpa/bin/pruned_transducer_statelessX/offline_server.py", line 277, in __init__
    self.nn_models = self._build_nn_model(nn_model_filename, num_device)
  File "/k2-sherpa/sherpa/bin/pruned_transducer_statelessX/offline_server.py", line 358, in _build_nn_model
    model = RnntConformerModel(
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. _sherpa.RnntConformerModel(filename: str, device: object = 'cpu', optimize_for_inference: bool = False)

Invoked with: kwargs: filename='./exp/cpu_jit-iter-3488000-avg-15.pt', left_context=0, right_context=0, decode_chunk_size=0, device='cpu', optimize_for_inference=False
```

I use this command to launch the server:
```
sherpa/bin/pruned_transducer_statelessX/offline_server.py \
    --port 6006 \
    --num-device 0 \
    --max-batch-size 10 \
    --max-wait-ms 5 \
    --feature-extractor-pool-size 5 \
    --nn-pool-size 1 \
    --nn-model-filename ./exp/cpu_jit-iter-3488000-avg-15.pt \
    --bpe-model-filename ./data/lang_bpe_500/bpe.model
```

Thank you! :)

**Comment by MolochKel** [comment]
Yeah, I was checking out master instead of tags/v1.0... My apologies.
