### ISSUE TITLE
Cannot load model trained with pruned_transducer_stateless2

### ISSUE THREAD

**Issue by ahazned** [k2-fsa/sherpa#2]
Hi,

First of all thanks for the effort, this will be an amazing framework to utilize the models trained with icefall&k2.

My issue is, I have trained a model using "pruned_transducer_stateless2" and I have an output model file: "/tmp/icefall/egs/librispeech/ASR/pruned_transducer_stateless2/exp_fp16/epoch-25.pt"

This model file works perfectly fine when I use it with "/tmp/icefall/egs/librispeech/ASR/transducer_stateless2/decode.py", but when I try to use this model in "offline_server.py" (as "nn_model_filename") it gives me the following error. Do I need to convert the model to another format to use it with sharpa? 

```
Traceback (most recent call last):
  File "offline_server.py", line 394, in <module>
    main()
  File "/tmp/miniconda3/envs/k2_/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "offline_server.py", line 357, in main
    offline_server = OfflineServer(
  File "offline_server.py", line 121, in __init__
    self.nn_models = self._build_nn_model(nn_model_filename, num_device)
  File "offline_server.py", line 189, in _build_nn_model
    model = RnntModel(
RuntimeError: PytorchStreamReader failed locating file constants.pkl: file not found
Exception raised from valid at /opt/conda/conda-bld/pytorch_1646755903507/work/caffe2/serialize/inline_container.cc:158 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x4d (0x7f0ae4ff41bd in /tmp/miniconda3/envs/k2_/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x68 (0x7f0ae4ff0838 in /tmp/miniconda3/envs/k2_/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: caffe2::serialize::PyTorchStreamReader::valid(char const*, char const*) + 0x8e (0x7f0b19c5dc3e in /tmp/miniconda3/envs/k2_/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #3: caffe2::serialize::PyTorchStreamReader::getRecordID(std::string const&) + 0x47 (0x7f0b19c5de07 in /tmp/miniconda3/envs/k2_/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #4: caffe2::serialize::PyTorchStreamReader::getRecord(std::string const&) + 0x45 (0x7f0b19c5ded5 in /tmp/miniconda3/envs/k2_/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #5: torch::jit::readArchiveAndTensors(std::string const&, std::string const&, std::string const&, c10::optional<std::function<c10::StrongTypePtr (c10::QualifiedName const&)> >, c10::optional<std::function<c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> > (c10::StrongTypePtr, c10::IValue)> >, c10::optional<c10::Device>, caffe2::serialize::PyTorchStreamReader&, c10::Type::SingletonOrSharedTypePtr<c10::Type> (*)(std::string const&), std::shared_ptr<torch::jit::DeserializationStorageContext>) + 0xac (0x7f0b1a7dde5c in /tmp/miniconda3/envs/k2_/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x2f64e99 (0x7f0b1a7d7e99 in /tmp/miniconda3/envs/k2_/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x2f66b4f (0x7f0b1a7d9b4f in /tmp/miniconda3/envs/k2_/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #8: torch::jit::load(std::shared_ptr<caffe2::serialize::ReadAdapterInterface>, c10::optional<c10::Device>, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >&) + 0x1af (0x7f0b1a7daeef in /tmp/miniconda3/envs/k2_/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #9: torch::jit::load(std::string const&, c10::optional<c10::Device>, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >&) + 0xad (0x7f0b1a7dc87d in /tmp/miniconda3/envs/k2_/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #10: torch::jit::load(std::string const&, c10::optional<c10::Device>) + 0x54 (0x7f0b1a7dc954 in /tmp/miniconda3/envs/k2_/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #11: sherpa::RnntModel::RnntModel(std::string const&, c10::Device, bool) + 0x81 (0x7f0ac2349b01 in /tmp/sherpa/build/lib/libsherpa_core.so)
frame #12: <unknown function> + 0x165ad (0x7f0ac25675ad in /tmp/sherpa/build/lib/_sherpa.cpython-38-x86_64-linux-gnu.so)
frame #13: <unknown function> + 0x6ca4 (0x7f0ac2557ca4 in /tmp/sherpa/build/lib/_sherpa.cpython-38-x86_64-linux-gnu.so)
<omitting python frames>
frame #20: <unknown function> + 0x16713 (0x7f0ac3031713 in /tmp/miniconda3/envs/k2_/lib/python3.8/site-packages/kaldifeat-1.15-py3.8-linux-x86_64.egg/_kaldifeat.cpython-38-x86_64-linux-gnu.so)
frame #44: __libc_start_main + 0xe7 (0x7f0b9b411c87 in /lib/x86_64-linux-gnu/libc.so.6)

```

**Comment by ahazned** [comment]
Ok, now I can load the model after exporting it by "icefall/egs/librispeech/ASR/transducer_stateless2/export.py" with "--jit 1"

**Comment by csukuangfj** [comment]
@ahazned 
Thanks for trying it. 

Could you leave some feedback/comments after using it? 

Thanks again.
