### ISSUE TITLE
The client terminal cannot use the multi-process program to send data

### ISSUE THREAD

**Issue by arbs-gpu** [k2-fsa/sherpa#248]
@csukuangfj 
The code for this client is in  
https://github.com/k2-fsa/sherpa/tree/master/triton/client/client.py

After my test, if you do not use multi-process mode, that is, send data to the server with a single thread, it can return normal recognition results. If you run the script directly (that is, use multi-process), the following error will be reported:
  
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 576, in _handle_results
    task = get()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 1 required positional argument: 'msg'

**Comment by csukuangfj** [comment]
@yuekaizhang  Could you please have a look?
