### ISSUE TITLE
`icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13` doesn't work with the `streaming_pruned_transducer_statelessX` server

### ISSUE THREAD

**Issue by YuriiMytiai** [k2-fsa/sherpa#279]
Hello,
I tried to use pretrained model `icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13` with both offline and streaming servers.
It works with offline server, but not with streaming server.
The error is the following:
`Traceback (most recent call last):
  File "/home/ubuntu/sherpa/sherpa/bin/streaming_pruned_transducer_statelessX/streaming_server.py", line 763, in <module>
    main()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/sherpa/sherpa/bin/streaming_pruned_transducer_statelessX/streaming_server.py", line 719, in main
    server = StreamingServer(
  File "/home/ubuntu/sherpa/sherpa/bin/streaming_pruned_transducer_statelessX/streaming_server.py", line 327, in __init__
    self.initial_states = self.model.get_encoder_init_states(
RuntimeError: Method 'get_init_state' is not defined.`
This method exists in the encoder that suppose to belong to model I tried to use (https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless2/conformer.py#L200) and I see it was added 6 month ago. 
So' it looks like model was exported with older version of the code. Does it mean that I need to install old sherpa version in order to be able to run streaming server with this model? Or is there some other solution for such cases without having few versions of icefall and sherpa installed?
Thank you!

**Comment by csukuangfj** [comment]
The error is expected.  A streaming server cannot work with a non-streaming model.

**Comment by YuriiMytiai** [comment]
I see, thank you!
