### ISSUE TITLE
Cannot compile under MacOS

### ISSUE THREAD

**Issue by jtrmal** [k2-fsa/sherpa#53]
Hi, when compiling under Mac OS X, I will get the following error
```
-- Python executable: /usr/local/opt/python@3.9/bin/python3.9
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'k2' has no attribute 'cmake_prefix_path'
-- K2_CMAKE_PREFIX_PATH:
CMake Error at /usr/local/Cellar/cmake/3.23.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find k2 (missing: location_k2_torch_api location_k2_log
  location_k2context location_k2fsa)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.23.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake/k2/k2Config.cmake:74 (find_package_handle_standard_args)
  cmake/k2.cmake:19 (find_package)
  CMakeLists.txt:44 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/jtrmal/projects/sherpa/build/temp.macosx-12-x86_64-cpython-39/CMakeFiles/CMakeOutput.log".
See also "/Users/jtrmal/projects/sherpa/build/temp.macosx-12-x86_64-cpython-39/CMakeFiles/CMakeError.log".
make: *** No rule to make target `_sherpa'.  Stop.
Traceback (most recent call last):
  File "/Users/jtrmal/projects/sherpa/setup.py", line 42, in <module>
    setuptools.setup(
  File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/usr/local/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/local/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/Users/jtrmal/projects/sherpa/cmake/cmake_extension.py", line 108, in build_extension
    raise Exception(
Exception:
Build sherpa failed. Please check the error message.
You can ask for help by creating an issue on GitHub.

Click:
	https://github.com/k2-fsa/sherpa/issues/new
```

**Comment by jtrmal** [comment]
I have (of course) k2 installed.
I have also found out that if I copy _k2 into site-packages:
```
 cp /usr/local/lib/python3.9/site-packages/k2-1.17.dev20220707+cpu.torch1.11.0-py3.9-macosx-12-x86_64.egg/_k2.cpython-39-darwin.so /usr/local/lib/python3.9/site-packages/```
 the process seems to continue but fails very early later on:
 ```
 -- Python executable: /usr/local/opt/python@3.9/bin/python3.9
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/k2/__init__.py", line 3, in <module>
    from _k2 import DeterminizeWeightPushingType
ImportError: dlopen(/usr/local/lib/python3.9/site-packages/_k2.cpython-39-darwin.so, 0x0002): Symbol not found: __ZN2k210GetContextEN3c106DeviceE
  Referenced from: /usr/local/lib/python3.9/site-packages/_k2.cpython-39-darwin.so
  Expected in: /usr/local/lib/python3.9/site-packages/libk2context.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/k2/__init__.py", line 8, in <module>
    raise ImportError(
ImportError: dlopen(/usr/local/lib/python3.9/site-packages/_k2.cpython-39-darwin.so, 0x0002): Symbol not found: __ZN2k210GetContextEN3c106DeviceE
  Referenced from: /usr/local/lib/python3.9/site-packages/_k2.cpython-39-darwin.so
  Expected in: /usr/local/lib/python3.9/site-packages/libk2context.dylib
Note: If you're using anaconda and importing k2 on MacOS,
      you can probably fix this by setting the environment variable:
  export DYLD_LIBRARY_PATH=$CONDA_PREFIX/lib/python3.9/site-packages:$DYLD_LIBRARY_PATH
-- K2_CMAKE_PREFIX_PATH:
CMake Error at /usr/local/Cellar/cmake/3.23.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find k2 (missing: location_k2_torch_api location_k2_log
  location_k2context location_k2fsa)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.23.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake/k2/k2Config.cmake:74 (find_package_handle_standard_args)
  cmake/k2.cmake:19 (find_package)
  CMakeLists.txt:44 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/jtrmal/projects/sherpa/build/temp.macosx-12-x86_64-cpython-39/CMakeFiles/CMakeOutput.log".
See also "/Users/jtrmal/projects/sherpa/build/temp.macosx-12-x86_64-cpython-39/CMakeFiles/CMakeError.log".
make: *** No rule to make target `_sherpa'.  Stop.
Traceback (most recent call last):
  File "/Users/jtrmal/projects/sherpa/setup.py", line 42, in <module>
    setuptools.setup(
  File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/usr/local/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/local/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/Users/jtrmal/projects/sherpa/cmake/cmake_extension.py", line 108, in build_extension
    raise Exception(
Exception:
Build sherpa failed. Please check the error message.
You can ask for help by creating an issue on GitHub.

Click:
	https://github.com/k2-fsa/sherpa/issues/new

 ```
 I wonder if it's something about wrong CUDA detection? Just because of the error (demangled)
` Symbol not found: _k2::GetContext(c10::Device)`

**Comment by csukuangfj** [comment]
> k2 should be up to date with github repo

Can you check that k2 is the latest one?

```
python3 -m k2.version
```

**Comment by csukuangfj** [comment]
> I have also found out that if I copy _k2 into site-packages:

If you have the latest k2 installed, you don't need to do this, I think.

**Comment by jtrmal** [comment]
```
$ python3 -m k2.version
Collecting environment information...

k2 version: 1.17
Build type: Release
Git SHA1: f910452c594ac57b9a6117ad9b353555f95d45d8
Git date: Mon Jul 4 10:26:28 2022
Cuda used to build k2:
cuDNN used to build k2:
Python version used to build k2: 3.9
OS used to build k2: macOS 12.4 21F79
CMake version: 3.23.2
GCC version: 13.1.6.13160021
CMAKE_CUDA_FLAGS:
CMAKE_CXX_FLAGS:   -Wno-unused-variable  -Wno-strict-overflow
PyTorch version used to build k2: 1.11.0
PyTorch is using Cuda:
NVTX enabled: False
With CUDA: False
Disable debug: True
Sync kernels : False
Disable checks: False
```

**Comment by csukuangfj** [comment]
I see.

>   /usr/local/share/cmake/k2/k2Config.cmake:74 (find_package_handle_standard_args)

`k2Config.cmake` is not installed into the expected location
`/usr/local/lib/python3.9/site-packages/k2-1.17.dev20220707+cpu.torch1.11.0-py3.9-macosx-12-x86_64.egg/k2/share/cmake/k2`

How did you install k2?

**Comment by jtrmal** [comment]
I just did `python3 setup.py install`

**Comment by jtrmal** [comment]
I have brew , btw, so that might mess with the paths
y.

**Comment by jtrmal** [comment]
```
$ python3 setup.py install | grep cmake
cmake version 3.23.2
CMake suite maintained and supported by Kitware (kitware.com/cmake).
cmake_path: /usr/local/bin/cmake
/usr/local/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
CMake Warning (dev) at /usr/local/Cellar/cmake/3.23.2/share/cmake/Modules/CMakeDependentOption.cmake:89 (message):
  Policy CMP0127 is not set: cmake_dependent_option() supports full Condition
  Syntax.  Run "cmake --help-policy CMP0127" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
  build/temp.macosx-12-x86_64-cpython-39/_deps/pybind11-src/CMakeLists.txt:91 (cmake_dependent_option)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at /usr/local/lib/python3.9/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /usr/local/lib/python3.9/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  cmake/torch.cmake:11 (find_package)
  CMakeLists.txt:279 (include)


-- Up-to-date: /Users/jtrmal/projects/k2/build/lib.macosx-12-x86_64-cpython-39/k2/share/cmake/k2/k2ConfigVersion.cmake
-- Up-to-date: /Users/jtrmal/projects/k2/build/lib.macosx-12-x86_64-cpython-39/k2/share/cmake/k2/k2Config.cmake
                cmake -DCMAKE_BUILD_TYPE=Release -DK2_WITH_CUDA=OFF -DPYTHON_EXECUTABLE=/usr/local/opt/python@3.9/bin/python3.9 -DK2_ENABLE_BENCHMARK=OFF  -DK2_ENABLE_TESTS=OFF  -DCMAKE_INSTALL_PREFIX=/Users/jtrmal/projects/k2/build/lib.macosx-12-x86_64-cpython-39/k2  /Users/jtrmal/projects/k2
creating build/bdist.macosx-12-x86_64/egg/k2/share/cmake
creating build/bdist.macosx-12-x86_64/egg/k2/share/cmake/k2
copying build/lib.macosx-12-x86_64-cpython-39/k2/share/cmake/k2/k2ConfigVersion.cmake -> build/bdist.macosx-12-x86_64/egg/k2/share/cmake/k2
copying build/lib.macosx-12-x86_64-cpython-39/k2/share/cmake/k2/k2Config.cmake -> build/bdist.macosx-12-x86_64/egg/k2/share/cmake/k2
```

**Comment by csukuangfj** [comment]
Can you post the all the logs of `python3 setup.py install`?

**Comment by jtrmal** [comment]
[install.log](https://github.com/k2-fsa/sherpa/files/9067875/install.log)

**Comment by csukuangfj** [comment]
Can you show the output of

```
ls -lh /usr/local/lib/python3.9/site-packages/*k2*

otool -l /usr/local/lib/python3.9/site-packages/_k2.cpython-39-darwin.so

ls -lh /usr/local/lib/python3.9/site-packages/k2-1.17.dev20220707+cpu.torch1.11.0-py3.9-macosx-12-x86_64.egg/lib

ls -lh /usr/local/lib/python3.9/site-packages/k2-1.17.dev20220707+cpu.torch1.11.0-py3.9-macosx-12-x86_64.egg/k2/share/cmake/k2
```

**Comment by jtrmal** [comment]
```
$ ls -lh /usr/local/lib/python3.9/site-packages/*k2*
-rwxr-xr-x  1 jtrmal  admin   1.0M Dec  7  2021 /usr/local/lib/python3.9/site-packages/_k2.cpython-36m-x86_64-linux-gnu.so
-rwxr-xr-x  1 jtrmal  admin    34K Dec  7  2021 /usr/local/lib/python3.9/site-packages/libk2_log.dylib
-rwxr-xr-x  1 jtrmal  admin   2.4M Dec  7  2021 /usr/local/lib/python3.9/site-packages/libk2context.dylib
-rwxr-xr-x  1 jtrmal  admin   453K Dec  7  2021 /usr/local/lib/python3.9/site-packages/libk2fsa.dylib

/usr/local/lib/python3.9/site-packages/k2:
total 496
-rw-r--r--   1 jtrmal  admin   2.5K Dec  7  2021 __init__.py
drwxr-xr-x  14 jtrmal  admin   448B Dec  7  2021 __pycache__
-rw-r--r--   1 jtrmal  admin   3.2K Dec  7  2021 array.py
-rw-r--r--   1 jtrmal  admin    33K Dec  7  2021 autograd.py
-rw-r--r--   1 jtrmal  admin   5.0K Dec  7  2021 autograd_utils.py
-rw-r--r--   1 jtrmal  admin   5.3K Dec  7  2021 ctc_loss.py
-rw-r--r--   1 jtrmal  admin   9.3K Dec  7  2021 dense_fsa_vec.py
-rw-r--r--   1 jtrmal  admin    56K Dec  7  2021 fsa.py
-rw-r--r--   1 jtrmal  admin    45K Dec  7  2021 fsa_algo.py
-rw-r--r--   1 jtrmal  admin   2.1K Dec  7  2021 fsa_properties.py
-rw-r--r--   1 jtrmal  admin   9.6K Dec  7  2021 nbest.py
-rw-r--r--   1 jtrmal  admin   9.4K Dec  7  2021 ops.py
drwxr-xr-x   4 jtrmal  admin   128B Dec  7  2021 ragged
drwxr-xr-x   5 jtrmal  admin   160B Dec  7  2021 sparse
-rw-r--r--   1 jtrmal  admin   8.5K Dec  7  2021 symbol_table.py
-rw-r--r--   1 jtrmal  admin    30K Dec  7  2021 utils.py
drwxr-xr-x   6 jtrmal  admin   192B Dec  7  2021 version

/usr/local/lib/python3.9/site-packages/k2-1.11.dev20211208+cpu.torch1.8.1.dist-info:
total 80
-rw-r--r--  1 jtrmal  admin     4B Dec  7  2021 INSTALLER
-rw-r--r--  1 jtrmal  admin    11K Dec  7  2021 LICENSE
-rw-r--r--  1 jtrmal  admin   5.9K Dec  7  2021 METADATA
-rw-r--r--  1 jtrmal  admin   3.2K Dec  7  2021 RECORD
-rw-r--r--  1 jtrmal  admin     0B Dec  7  2021 REQUESTED
-rw-r--r--  1 jtrmal  admin   109B Dec  7  2021 WHEEL
-rw-r--r--  1 jtrmal  admin    59B Dec  7  2021 direct_url.json
-rw-r--r--  1 jtrmal  admin     7B Dec  7  2021 top_level.txt

/usr/local/lib/python3.9/site-packages/k2-1.17.dev20220707+cpu.torch1.11.0-py3.9-macosx-12-x86_64.egg:
total 3552
drwxr-xr-x   9 jtrmal  admin   288B Jul  7 19:34 EGG-INFO
drwxr-xr-x   3 jtrmal  admin    96B Jul  7 19:34 __pycache__
-rwxr-xr-x   1 jtrmal  admin   1.7M Jul  7 19:34 _k2.cpython-39-darwin.so
-rw-r--r--   1 jtrmal  admin   418B Jul  7 19:34 _k2.py
drwxr-xr-x  25 jtrmal  admin   800B Jul  7 19:34 k2

/usr/local/lib/python3.9/site-packages/k2_fsa-0.0.5.dist-info:
total 48
-rw-r--r--  1 jtrmal  admin   1.4K Dec  7  2021 LICENSE
-rw-r--r--  1 jtrmal  admin   7.2K Dec  7  2021 METADATA
-rw-r--r--  1 jtrmal  admin   982B Dec  7  2021 RECORD
-rw-r--r--  1 jtrmal  admin    93B Dec  7  2021 WHEEL
-rw-r--r--  1 jtrmal  admin     3B Dec  7  2021 top_level.txt

```

**Comment by jtrmal** [comment]
```
$ otool -l /usr/local/lib/python3.9/site-packages/_k2.cpython-39-darwin.so
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /usr/local/lib/python3.9/site-packages/_k2.cpython-39-darwin.so (No such file or directory)
```

**Comment by jtrmal** [comment]
```
$ ls -lh /usr/local/lib/python3.9/site-packages/k2-1.17.dev20220707+cpu.torch1.11.0-py3.9-macosx-12-x86_64.egg/lib
ls: /usr/local/lib/python3.9/site-packages/k2-1.17.dev20220707+cpu.torch1.11.0-py3.9-macosx-12-x86_64.egg/lib: No such file or directory

$ ls -lh /usr/local/lib/python3.9/site-packages/k2-1.17.dev20220707+cpu.torch1.11.0-py3.9-macosx-12-x86_64.egg/k2/share/cmake/k2

total 16
-rw-r--r--  1 jtrmal  admin   2.5K Jul  7 19:34 k2Config.cmake
-rw-r--r--  1 jtrmal  admin   436B Jul  7 19:34 k2ConfigVersion.cmake
```

**Comment by jtrmal** [comment]
it seems there are multiple versions of k2, how about removing all of them?
Not sure why it didn't happen automatically

**Comment by csukuangfj** [comment]
You can remove everything containing `k2` in their name under the directory
/usr/local/lib/python3.9/site-packages

Also, please remove the directory.
`/usr/local/share/cmake/k2`

**Comment by csukuangfj** [comment]
After reinstalling k2, everything should work.

While installing sherpa, please use
```
python3 setup.py install
```
to install the latest version. 

`pip install k2-sherpa` does not install the one from the latest master.

**Comment by jtrmal** [comment]
yeah, after cleanup I had success installing sherpa
Thanks!

**Comment by csukuangfj** [comment]
Great!
