### ISSUE TITLE
sherpa/bin/streaming_pruned_transducer_statelessX/streaming_server.py  throws errors under heavy load

### ISSUE THREAD

**Issue by ngoel17** [k2-fsa/sherpa#84]
I have seen the following types of errors:
File "/mnt/dsk4/sherpa/./sherpa/bin/streaming_pruned_transducer_statelessX/streaming_server.py", line 499, in handle_connection_impl
    await socket.send(result)
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 620, in send
    await self.ensure_open()
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 930, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received

reducing ping_interval to 5 sec and increasing the ping_timeout to 40 sec does not help. 
I use these parameters currently:
  --max-batch-size 500 \
  --max-wait-ms 250 \
  --max-active-connections 500 \
and I am using 20 to 50 simultaneous clients. Ideally, I would like to use 100 simultaneous clients.

**Comment by csukuangfj** [comment]
Does this happen also for the offine_server.py?

**Comment by ngoel17** [comment]
I didn't quite figure out how to correctly launch the offline server. I get the following error. However, client-server architecture is of no interest in the case of offline to me. I did try exporting without the streaming option. 
------------------------
2022-07-31 01:44:32,646 INFO [offline_server.py:576] {'port': 6007, 'num_device': 1, 'max_batch_size': 500, 'max_wait_ms': 250.0, 'feature_extractor_pool_size': 5, 'nn_pool_size\
': 1, 'nn_model_filename': '/home/ngoel/_k2/pruned_transducer_stateless2/exp_old/cpu_jit.pt', 'bpe_model_filename': '/home/ngoel/_k2/data/lang_bpe_500/bpe.model', 'token_filenam\
e': None, 'max_message_size': 1048576, 'max_queue_size': 32, 'max_active_connections': 500, 'decoding_method': 'modified_beam_search', 'num_active_paths': 4}
2022-07-31 01:44:35,291 INFO [offline_server.py:367] started
2022-07-31 01:44:35,292 INFO [server.py:707] server listening on [::]:6007
2022-07-31 01:44:35,292 INFO [server.py:707] server listening on 0.0.0.0:6007
2022-07-31 01:44:49,374 INFO [server.py:642] connection open
2022-07-31 01:44:49,374 INFO [offline_server.py:554] Connected: ('127.0.0.1', 53844). Number of connections: 1/500
2022-07-31 01:44:49,376 INFO [offline_server.py:538] Disconnected: ('127.0.0.1', 53844). Number of connections: 0/500
2022-07-31 01:44:49,377 ERROR [server.py:234] connection handler failed
Traceback (most recent call last):
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/websockets/legacy/server.py", line 232, in handler
    await self.ws_handler(self)
  File "/mnt/dsk4/sherpa/./sherpa/bin/pruned_transducer_statelessX/offline_server.py", line 533, in handle_connection
    await self.handle_connection_impl(socket)
  File "/mnt/dsk4/sherpa/./sherpa/bin/pruned_transducer_statelessX/offline_server.py", line 560, in handle_connection_impl
    samples = await self.recv_audio_samples(socket)
  File "/mnt/dsk4/sherpa/./sherpa/bin/pruned_transducer_statelessX/offline_server.py", line 413, in recv_audio_samples
    header = await socket.recv()
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 553, in recv
    await self.ensure_open()
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 930, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2022-07-31 01:44:49,377 INFO [server.py:260] connection closed
2022-07-31 01:44:50,491 INFO [server.py:642] connection open
2022-07-31 01:44:50,491 INFO [offline_server.py:554] Connected: ('127.0.0.1', 53846). Number of connections: 1/500
2022-07-31 01:44:50,502 INFO [offline_server.py:538] Disconnected: ('127.0.0.1', 53846). Number of connections: 0/500
2022-07-31 01:44:50,502 ERROR [server.py:234] connection handler failed
Traceback (most recent call last):

**Comment by csukuangfj** [comment]
> I didn't quite figure out how to correctly launch the offline server. 

Looks to me that the client closes the connection. Don't know what's the exact reason for the above error logs.

**Comment by ngoel17** [comment]
Issue resolved with release 1.0
